**use of Asterisks in Python**


Most of us use asterisks as multiplication and power operators, but they also have a wide range of operations 
being used as a prefix operator in Python. After reading this article, you will get to know the full usage of asterisks.



In [1]:
## declaring variables
a, b = 2,3

## multiplication
print("Multiplication of 2 and 3 is {}".format(a * b))

## as power operator
print("2 power 3 is {}".format(a ** b))

Multiplication of 2 and 3 is 6
2 power 3 is 8


**Unpacking Using**

In [3]:
## general approach
nums = [i for i in range(1, 6)]
a = nums[0]
b = nums[1:]
print(a, *b)

1 2 3 4 5


In [10]:
x=[1,2,3,4,5,6]
print(x)
print(*x)
print(*x,sep='')
print(*x,sep='-')

[1, 2, 3, 4, 5, 6]
1 2 3 4 5 6
123456
1-2-3-4-5-6


In [11]:
## hard approach
squares = [i ** 2 for i in range(1, 6)]
a = squares[0]
b = []
for i in range(1, len(squares)):
    b.append(squares[i])
print(a, b)

1 [4, 9, 16, 25]


**Note**- Unpacking can work on tuples and sets the same as it does with the lists. Let's see some examples of it.

In [12]:
a, *b, c = (1, 2, 3, 4, 5)
print(a, b, c)

1 [2, 3, 4] 5


In [13]:
nums = [i for i in range(1, 6)]

## a will be 1 and b will be a list containing remaining elements
a, *b = nums
print(a, b)

1 [2, 3, 4, 5]


In [14]:
a, *b, c = {1, 4, 9, 16, 25}
print(a, b, c)

1 [4, 9, 16] 25


In [15]:
## combining a tuple, list, set
nums = [1, 2, 3]
nums2 = (4, 5, 6)
nums3 = {7, 8, 9}

## we convert the combined elements into any iterable we want
## here i am converting into a list
_list = [*nums, *nums2, *nums3]
_tuple = (*nums, *nums2, *nums3)
_set = {*nums, *nums2, *nums3}

print(type(_list))
print(_list)
print("------------------------")
print(type(_tuple))
print(_tuple)
print("------------------------")
print(type(_set))
print(_set)

<class 'list'>
[1, 2, 3, 4, 5, 6, 8, 9, 7]
------------------------
<class 'tuple'>
(1, 2, 3, 4, 5, 6, 8, 9, 7)
------------------------
<class 'set'>
{1, 2, 3, 4, 5, 6, 7, 8, 9}


**Nested Unpacking**

In [19]:
languages = ["Python", "HTML", "CSS", "JS"]

## unpacking
[[first_letter, *remaining], *other] = languages

print(first_letter, remaining, other)

P ['y', 't', 'h', 'o', 'n'] ['HTML', 'CSS', 'JS']


Unpacking Using **

In [20]:
## sample dictionary
person = {"name":"John", "age":19, "year_of_passing":"2021"}
string = "Name:-{name} Year Of Graduation:-{year_of_passing} Age:-{age}".format(**person)
print(string)

Name:-John Year Of Graduation:-2021 Age:-19


Asterisks In Functions

The * operator is used to call a function by unpacking an iterable

In [22]:
nums = [i for i in range(1, 6)]
## passsing list using the *
print(*nums)

1 2 3 4 5


In [27]:
def average(*nums):
    return sum(nums) / len(nums)

In [28]:
print(average(1, 2, 3, 4, 5))

3.0


In [29]:
def keyword_only(*items, _list, default = False):
    print(items)
    print(_list)
    print(default)

In [30]:
nums = [i ** 2 for i in range(1, 6)]
## calling the function
keyword_only(1, 2, 3, 4, 5, _list = nums, default = True)

(1, 2, 3, 4, 5)
[1, 4, 9, 16, 25]
True


In [31]:
def sqr(x):
    return x**2

In [32]:
sqr(3)

9

In [37]:
#multiple input
sqr(1,2)     #error

TypeError: sqr() takes 1 positional argument but 2 were given

In [35]:
import numpy as np
sqr=np.vectorize(sqr)
sqr([1,2])

array([1, 4])

In [38]:
#method 2
def squr(*x):
    return x

In [39]:
squr(3)

(3,)

In [40]:
sqr([1,2,3])

array([1, 4, 9])

In [43]:
sqr([1,2,3,4,5])

array([ 1,  4,  9, 16, 25])

Keyword-Only Arguments Without Positional Arguments

In [44]:
def _sample(*, name):
    print(name)

In [46]:
_sample(name='ravi')

ravi
