In [3]:
myfile = open("cars.csv", "r")

In [4]:
fileData = myfile.read()
print(type(fileData))

<class 'str'>


In [5]:
print(fileData)

"speed","dist"
4,2
4,10
7,4
7,22
8,16
9,10
10,18
10,26
10,34
11,17
11,28
12,14
12,20
12,24
12,28
13,26
13,34
13,34
13,46
14,26
14,36
14,60
14,80
15,20
15,26
15,54
16,32
16,40
17,32
17,40
17,50
18,42
18,56
18,76
18,84
19,36
19,46
19,68
20,32
20,48
20,52
20,56
20,64
22,66
23,54
24,70
24,92
24,93
24,120
25,85



In [6]:
myfile.close()

In [7]:
newdata = fileData.split()
print(type(newdata))
print(newdata)

<class 'list'>
['"speed","dist"', '4,2', '4,10', '7,4', '7,22', '8,16', '9,10', '10,18', '10,26', '10,34', '11,17', '11,28', '12,14', '12,20', '12,24', '12,28', '13,26', '13,34', '13,34', '13,46', '14,26', '14,36', '14,60', '14,80', '15,20', '15,26', '15,54', '16,32', '16,40', '17,32', '17,40', '17,50', '18,42', '18,56', '18,76', '18,84', '19,36', '19,46', '19,68', '20,32', '20,48', '20,52', '20,56', '20,64', '22,66', '23,54', '24,70', '24,92', '24,93', '24,120', '25,85']


In [8]:
import os

In [9]:
os.mkdir("c:\\newdir")

In [10]:
print(os.getcwd())

C:\Users\DeLL\Downloads\data mining


In [11]:
os.mkdir('newdir')

In [12]:
os.chdir('newdir')

In [13]:
print(os.getcwd())

C:\Users\DeLL\Downloads\data mining\newdir


In [14]:
os.chdir('..\\')

In [15]:
print(os.getcwd())

C:\Users\DeLL\Downloads\data mining


In [ ]:
import numpy as np
A =  np.array([[1,2], [3,4], [5,6]])
print(A.size)
print(A.shape)
B = A.reshape([6,1])
print(B)

c = B.T
print(c.shape)
print(c)


In [ ]:
import pandas as pd
csvdf = pd.read_csv("NSEI.csv")

In [ ]:
print(csvdf)

In [1]:
import numpy as np
arrA = np.array([1,2,3,4,5])
print(type(arrA))
print(arrA)
print(arrA[0])
print(arrA[2])

<class 'numpy.ndarray'>
[1 2 3 4 5]
1
3


In [ ]:
a = np.ones((3,3))
a[0][0] = 0
a[1] = [1,2,3]
print(a)

In [ ]:
b = 2 * a
print(b)

In [ ]:
c = a + b
print(c)

In [ ]:
cinv = np.linalg.inv(c)
print(cinv)
print(cinv.shape)

In [ ]:
print(c.T)

In [ ]:
myrange = np.linspace(0, 0, 25).reshape(5,5).T
print(myrange)

In [21]:
a = np.array([1,2,3,4]).reshape(2,2)
print("Matrix a\r\n",a)
b = np.linalg.inv(a)
print("Matrix b\r\n",b)
c = a.dot(b)
print("Matric C: Dotproduct\r\n",c)

Matrix a
 [[1 2]
 [3 4]]
Matrix b
 [[-2.   1. ]
 [ 1.5 -0.5]]
Matric C: Dotproduct
 [[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


In [ ]:

a = np.array([1,2,3,4,5,6]).reshape(3,2)
x = a > 3
print(type(x))
print(x)
a[x] = -1
print(a)

In [16]:
import numpy as np
a = np.array(range(1,15))
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [17]:
arr4 = np.ones([3,4])
arr4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
arr4[2,1] = 0
arr4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 0., 1., 1.]])

In [19]:
arr4[1] = [1,2,3,4]
arr4

array([[1., 1., 1., 1.],
       [1., 2., 3., 4.],
       [1., 0., 1., 1.]])

In [20]:
print(arr4.ravel())

[1. 1. 1. 1. 1. 2. 3. 4. 1. 0. 1. 1.]
